language: node_js
node_js:
  - "12"

script: "yarn test"

jobs:
  include:
    - stage: unit tests
      script:
        - yarn install
        - yarn test
        - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
