name: Vue Swatches Publish Docs

on:
  release:
    types: [created, edited]

jobs:
  publish-docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn docs:build
      - uses: crazy-max/ghaction-github-pages@v1.4.0
        with:
          build_dir: docs/.vuepress/dist
          committer_name: Diego Jara
          committer_email: diegojara6@gmail.com
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
